### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by jecc002** [hzhu212/rayinvr#1]
Hi, 

Thanks for this. It seems to have compiled fine but with the mix of new and original parts here I'm not sure if the failure to run is a code issue or just in the modified input files I'm interpreting should work. If you have an example that should run with this you could share it would be great.

**Comment by hzhu212** [comment]
Thanks for your feedback, I thought no one would ever find here...🤣🤣

I have uploaded error-free example datasets, and also updated README. Feel free to try it, good luck!

**Comment by hzhu212** [comment]
I will close this issue if you don't have further questions.

PS: don't forget to star this repo if it helps.:grin:

**Comment by jecc002** [comment]
Thanks so much – will give this a go!

Jennifer

Dr Jennifer Eccles
Senior Lecturer
School of Environment
University of Auckland
Rm 302 735, Science Centre, 23 Symonds St, Auckland, New Zealand
Private Bag 92019, Auckland 1142, New Zealand
Ph +64 9 9238092 or +64 212035279
j.eccles@auckland.ac.nz
