### ISSUE TITLE
Makefile Error

### ISSUE THREAD

**Issue by sd104400** [hzhu212/rayinvr#2]
Hi Thanks a lot for sharing the instruction of compiling rayinvr in Windows 10, but I couldn't manage to do so. 
I installed GNU-Make 3.81 and Mingw-w64, and attempted to build executable, for example tramp, in its folder.

The error is 

> cd ../pltlib/; "make" pltsub.o
> The system cannot find the path specified.
> make: *** [../pltlib//pltsub.o] Error 1It seems that the system cannot find the path specified

I though it's probably because of the double "/" in the path of pltsub.o and I edited the makefile a bit. Now it can get the building process started but ended up with another error:

> process_begin: CreateProcess(NULL, # unilink main.o trc.o atrc.o adjpt.o rngkta.o plt.o misc.o amp.o hdw.o calmod.o blkdat.o ../pltlib/pltsub.o ../pltlib/pltlib.o, ...) failed.
> make (e=2): The system cannot find the file specified.
> make: *** [../build/tramp] Error 2

I'm not experienced with this sort of compiling processes and do you have ideas what could be issue? Thanks!

**Comment by hzhu212** [comment]
@sd104400 What command did you use to build `tramp`?

Enter the root directory of  this project from command line, and run the following commands should work:

```sh
cd tramp
make tramp FC=gfortran CC=gcc
```

**Comment by sd104400** [comment]
Hi,

Thanks for the reply! I have sorted out the issue. It was because I used the older version of the compilers from Mingw-w64. I updated to the latest version and it now works! 

However, I failed to compile _rayplot_ . I guess _rayplot_ is not supposed to be used in this environment.

**Comment by sd104400** [comment]
Also I wonder if the programs in the _misc_ folder, particularly, _dmplstsqr_ can be compiled by any means?

Thanks!

**Comment by sd104400** [comment]
Hi I've modified the program code following your instruction. It is compiled and now works!
